version: "3"
services:
  ui:
    container_name: beta.ardictech.com
    hostname: beta.ardictech.com
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
