import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../../components/header";

import styles from "../../styles/About.module.css";

import tr from "../../locales/tr";
import en from "../../locales/en";

const About = () => {
  const router = useRouter();
  const { locale } = router;
  const t = locale === "en" ? en : tr;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <div>{t.page.about.title}</div>
    </div>
  );
};

export default About;
